name: EApi
version: ${version}
main: top.e404.eapi.EApi
api-version: 1.13
authors: [ 404E ]
commands:
  eapi:
    description: 插件主命令
libraries:
  # - io.ktor:ktor-server-core-jvm:3.3.3
  # - io.ktor:ktor-server-cio-jvm:3.3.3
  # - io.ktor:ktor-server-call-logging-jvm:3.3.3
  - org.openjdk.nashorn:nashorn-core:15.7
permissions:
  eapi.admin:
    default: op
    description: 允许使用插件管理指令